package SimuladorSALT;

/*
 * ventanaGrafica.java
 *
 * Created on 9 de agosto de 2003, 9:11
 */

import org.jfree.data.xy.XYDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;
import org.jfree.chart.*;
import org.jfree.chart.plot.*;
import java.awt.image.*;
import java.util.ArrayList;

/**
 *
 * @author  RYM
 */
public class ventanaGrafica extends java.awt.Frame {
    
  BufferedImage grafica = null;

    
  /** Creates new form ventanaGrafica */
  public ventanaGrafica(ArrayList<Double> tamanoCola,ArrayList<Double> tiempoCola,int tipo) {
	  if(tipo==1){
	  this.grafica=this.creaImagenColas(tamanoCola,tiempoCola);
	  }else{
		  if(tipo==2){
			  this.grafica=this.creaImagenTiempoEspera(tamanoCola, tiempoCola);
		  }
		  else{
			  this.grafica=this.creaImagenTiempoAterrizaje(tamanoCola,tiempoCola);
		  }
		  
	  }
	  initComponents();
  }
    
  /** This method is called from within the constructor to
  * initialize the form.
  * WARNING: Do NOT modify this code. The content of this method is
  * always regenerated by the Form Editor.
  */
  private void initComponents() {
        
    addWindowListener(new java.awt.event.WindowAdapter() {
       public void windowClosing(java.awt.event.WindowEvent evt) {
            exitForm(evt);
       }
    });
        
    pack();
  }
    
  /** Exit the Application */
  private void exitForm(java.awt.event.WindowEvent evt) {
    System.exit(0);
  }
    
  /**
  * @param args the command line arguments
  */

  
  public BufferedImage creaImagenColas(ArrayList<Double> tamanoCola,ArrayList<Double> tiempoCola)
  {
    XYSeries series = new XYSeries("Evolucion");
	for(int i=0;i<tamanoCola.size();i++){    
		series.add(tiempoCola.get(i), tamanoCola.get(i));
	   
	}
    XYDataset juegoDatos= new XYSeriesCollection(series);
        
    JFreeChart chart = 
     ChartFactory.createXYLineChart("Comportamiento de Colas",  
        "Tiempo","Numero de aviones",juegoDatos,PlotOrientation.VERTICAL,
        false,
        false, 
        true                // Show legend
        );
            
    BufferedImage image = chart.createBufferedImage(800,400);   
     return image;
 }
  
  public BufferedImage creaImagenTiempoEspera(ArrayList<Double> tamanoCola,ArrayList<Double> tiempoCola)
  {
    XYSeries series = new XYSeries("Evolucion");
	for(int i=0;i<tamanoCola.size();i++){    
		series.add(tiempoCola.get(i), tamanoCola.get(i));
	   
	}
    XYDataset juegoDatos= new XYSeriesCollection(series);
        
    JFreeChart chart = 
     ChartFactory.createXYLineChart("Comportamiento tiempo de espera",  
        "Numero de aviones aterrizados","Tiempo de espera",juegoDatos,PlotOrientation.VERTICAL,
        false,
        false, 
        true                // Show legend
        );
            
    BufferedImage image = chart.createBufferedImage(800,400);   
     return image;
 }
  
  
  public BufferedImage creaImagenTiempoAterrizaje(ArrayList<Double> tamanoCola,ArrayList<Double> tiempoCola)
  {
    XYSeries series = new XYSeries("Evolucion");
	for(int i=0;i<tamanoCola.size();i++){    
		series.add(tiempoCola.get(i), tamanoCola.get(i));
	   
	}
    XYDataset juegoDatos= new XYSeriesCollection(series);
        
    JFreeChart chart = 
     ChartFactory.createXYLineChart("Comportamiento tiempo aterrizaje",  
        "Numero de aterrizajes","Tiempo de aterrizaje",juegoDatos,PlotOrientation.VERTICAL,
        false,
        false, 
        true                // Show legend
        );
            
    BufferedImage image = chart.createBufferedImage(800,400);   
     return image;
 }
 
 public void paint(java.awt.Graphics g) {
   //super.paint(g);
   
g.drawImage(grafica,60,60,null);
 }
       
}